### ISSUE TITLE
Mana spring totem not giving mana

### ISSUE THREAD

**Issue by Daribon** [Crestfall/JadefireTracker#118]
Mana spring totem doesn't give any mana to players atm.

**Comment by AsuraDev** [comment]
Mana spring totem does indeed give mana, but it is not shown in combat log.

**Comment by AsuraDev** [comment]
Fixed. Will be on on test realm tomorrow.

**Comment by Daribon** [comment]
Not fixed, mana spring totem currently gives players 0 mana.
![manaspring](https://cloud.githubusercontent.com/assets/6137576/8394150/ff98e512-1d2a-11e5-81ef-f09d084c9de8.png)

**Comment by AsuraDev** [comment]
This is fixed. You gain 0 mana when you're at full mana.
